---

language: python
python:
  - "3.6"
services:
  - docker
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pipenv run molecule --version
  - pipenv run ansible --version
  - pipenv run molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
