---

- import_tasks: import_os_vars.yml

- name: Get latest version
  uri:
    url: "{{ bitwarden_version_url }}"
    body_format: json
  changed_when: false
  register: bitwarden_version_json

- name: Set variables
  set_fact:
    bitwarden_version: "{{ bitwarden_version_json.json.name }}"

- name: Install
  become: true
  apt:
    deb: "{{ bitwarden_url }}/v{{ bitwarden_version }}/Bitwarden-{{ bitwarden_version }}-{{ package_type }}"
    state: present
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
